# Generated by Django 3.2.14 on 2022-07-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_rename_drinks_drink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='descriptions',
            new_name='description',
        ),
    ]
